import { useMemo } from "react";

export function useDashboardCoreConfigs({
  search,
  setSearch,
  leaderboardPageSize,
  handleLeaderboardPageSizeChange,
  topLeaderboard,
  setTopLeaderboard,
  canRunManualSnapshot,
  onRefreshLeaderboard,
  runManualSnapshot,
  snapshotRunning,
  exportLeaderboardCsv,
  leaderboardPagination,
  onPrevLeaderboardPage,
  onNextLeaderboardPage,
  leaderboardSort,
  deltaMetric,
  setDeltaMetric,
  showTotalDelta,
  setShowTotalDelta,
  moversPageSize,
  handleMoversPageSizeChange,
  topDelta,
  setTopDelta,
  exportDeltaCsv,
  deltaPayload,
  movers,
  moversPagination,
  onPrevMoversPage,
  onNextMoversPage,
  deltaSort,
  anomalyMinDelta,
  setAnomalyMinDelta,
  anomaliesPageSize,
  handleAnomaliesPageSizeChange,
  exportAnomaliesCsv,
  anomalySort,
  anomaliesPagination,
  onPrevAnomaliesPage,
  onNextAnomaliesPage,
}) {
  const leaderboardConfig = useMemo(
    () => ({
      search,
      setSearch,
      pageSize: leaderboardPageSize,
      setPageSize: handleLeaderboardPageSizeChange,
      top: topLeaderboard,
      setTop: setTopLeaderboard,
      canRunManualSnapshot,
      onRefresh: onRefreshLeaderboard,
      runManualSnapshot,
      snapshotRunning,
      exportCsv: exportLeaderboardCsv,
      startIndex: leaderboardPagination.startIndex,
      endIndex: leaderboardPagination.endIndex,
      totalRows: leaderboardPagination.totalRows,
      clampedPage: leaderboardPagination.clampedPage,
      totalPages: leaderboardPagination.totalPages,
      onPrevPage: onPrevLeaderboardPage,
      onNextPage: onNextLeaderboardPage,
      sort: leaderboardSort,
      visibleRows: leaderboardPagination.visibleRows,
    }),
    [
      search,
      setSearch,
      leaderboardPageSize,
      handleLeaderboardPageSizeChange,
      topLeaderboard,
      setTopLeaderboard,
      canRunManualSnapshot,
      onRefreshLeaderboard,
      runManualSnapshot,
      snapshotRunning,
      exportLeaderboardCsv,
      leaderboardPagination,
      onPrevLeaderboardPage,
      onNextLeaderboardPage,
      leaderboardSort,
    ]
  );

  const moversConfig = useMemo(
    () => ({
      deltaMetric,
      setDeltaMetric,
      showTotalDelta,
      setShowTotalDelta,
      pageSize: moversPageSize,
      setPageSize: handleMoversPageSizeChange,
      topDelta,
      setTopDelta,
      exportCsv: exportDeltaCsv,
      deltaPayload,
      rows: movers,
      startIndex: moversPagination.startIndex,
      endIndex: moversPagination.endIndex,
      totalRows: moversPagination.totalRows,
      clampedPage: moversPagination.clampedPage,
      totalPages: moversPagination.totalPages,
      onPrevPage: onPrevMoversPage,
      onNextPage: onNextMoversPage,
      sort: deltaSort,
      visibleRows: moversPagination.visibleRows,
    }),
    [
      deltaMetric,
      setDeltaMetric,
      showTotalDelta,
      setShowTotalDelta,
      moversPageSize,
      handleMoversPageSizeChange,
      topDelta,
      setTopDelta,
      exportDeltaCsv,
      deltaPayload,
      movers,
      moversPagination,
      onPrevMoversPage,
      onNextMoversPage,
      deltaSort,
    ]
  );

  const anomaliesConfig = useMemo(
    () => ({
      minDelta: anomalyMinDelta,
      setMinDelta: setAnomalyMinDelta,
      pageSize: anomaliesPageSize,
      setPageSize: handleAnomaliesPageSizeChange,
      exportCsv: exportAnomaliesCsv,
      sort: anomalySort,
      startIndex: anomaliesPagination.startIndex,
      endIndex: anomaliesPagination.endIndex,
      totalRows: anomaliesPagination.totalRows,
      clampedPage: anomaliesPagination.clampedPage,
      totalPages: anomaliesPagination.totalPages,
      onPrevPage: onPrevAnomaliesPage,
      onNextPage: onNextAnomaliesPage,
      visibleRows: anomaliesPagination.visibleRows,
    }),
    [
      anomalyMinDelta,
      setAnomalyMinDelta,
      anomaliesPageSize,
      handleAnomaliesPageSizeChange,
      exportAnomaliesCsv,
      anomalySort,
      anomaliesPagination,
      onPrevAnomaliesPage,
      onNextAnomaliesPage,
    ]
  );

  return {
    leaderboardConfig,
    moversConfig,
    anomaliesConfig,
  };
}
